/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
export function reduce(a: number, b: number): number
export function multiply(a: number, b: number): number
